# Generated by Django 5.2.1 on 2025-09-11 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=128, null=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后打开时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='video.category')),
            ],
            options={
                'verbose_name': '合集',
                'verbose_name_plural': '合集',
                'db_table': 'collection',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=128, null=True)),
                ('srt_path', models.CharField(blank=True, max_length=128, null=True)),
                ('translated_srt_path', models.CharField(blank=True, help_text='翻译字幕文件路径', max_length=128, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('video_length', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chapters', models.JSONField(blank=True, default=list, help_text='视频章节信息，JSON格式存储', null=True)),
                ('notes', models.TextField(blank=True, help_text='视频笔记，Markdown格式，限制8000字符', max_length=8000, null=True)),
                ('mindmap_content', models.JSONField(blank=True, default=dict, help_text='思维导图内容，JSON格式存储', null=True)),
                ('video_source', models.CharField(blank=True, choices=[('bilibili', 'Bilibili'), ('youtube', 'YouTube'), ('ar_glass', 'AR Glass'), ('upload', 'Upload')], help_text='视频来源', max_length=20, null=True)),
                ('raw_lang', models.CharField(blank=True, choices=[('en', 'English'), ('zh', 'Chinese'), ('jp', 'Japanese')], help_text='视频原始语言', max_length=5, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="标签列表，如['tools', 'afternoon', 'tutorial']", null=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后打开时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='video.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='video.collection')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Generated filename for storage', max_length=255)),
                ('original_name', models.CharField(help_text='Original filename from user', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path from MEDIA_ROOT', max_length=500)),
                ('file_type', models.CharField(help_text="MIME type like 'image/jpeg'", max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('context_type', models.CharField(choices=[('notes', 'Notes'), ('mindmap', 'Mindmap')], help_text='Where this attachment is used', max_length=20)),
                ('context_id', models.CharField(blank=True, help_text='Mindmap node ID when used in mindmap', max_length=100)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='False for soft delete')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='video.video')),
            ],
            options={
                'db_table': 'video_attachment',
                'ordering': ['-upload_time'],
                'indexes': [models.Index(fields=['video', 'context_type'], name='video_attac_video_i_d88444_idx'), models.Index(fields=['video', 'context_id'], name='video_attac_video_i_72e68a_idx')],
            },
        ),
    ]
